---
apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
data:
  password: >-
    VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: bmV0Ym94
metadata:
  name: netbox-db-secret
  namespace: netbox
